### ISSUE TITLE
glium issue

### ISSUE THREAD

**Issue by virtualritz** [turnage/valora#44]
I am seeing [this](https://github.com/glium/glium/issues/1648) on macOS 10.15.4 when I try the first sample from the guide. I tried with both `stable` and `nightly`.
```
thread 'main' panicked at 'gl function was not loaded', /Users/moritz/code/generative/target/release/build/glium-026141f5ee527852/out/gl_bindings.rs:2535:13
```

Not sure if I should report this upstream and re-open the `glium` ticket?

**Comment by turnage** [comment]
Unfortunately I don't have access to macOS to inspect this.

There are newer versions of glium available that might work if you don't suspect your OpenGL installation.

**Comment by virtualritz** [comment]
Bumping `glium` has breaking changes for the `glium::glutin` crate. I went through all of them and thought I'd have a pull request ready but I got stuck at last.

Specifically `glium::glutin::EventsLoop` is now `glium::glutin::event_loop::EventLoop` and no longer has the `poll_events()` function. I believe it is replaced by [`run()`](https://docs.rs/glutin/0.24.0/glutin/event_loop/struct.EventLoop.html#method.run) but the closure it takes has two additional arguments that `poll_events()` didn't have.

I never used these crates, so I'm out of my depth there.

**Comment by u-ashish** [comment]
+1 same issue on MacOS

**Comment by dp-pgh** [comment]
Ran into this issues as well, here is a full backtrace. Possibly related to Apple deprecating OpenGL and OpenCL for MacOS >= 10.14 in favor of proprietary technology.

```
$ RUST_BACKTRACE=full cargo run --release
    Finished release [optimized] target(s) in 1.08s
     Running `target/release/art`
thread 'main' panicked at 'gl function was not loaded', /Users/pskrz/repos/art/target/release/build/glium-026141f5ee527852/out/gl_bindings.rs:2535:13
stack backtrace:
   0:        0x104e05795 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
   1:        0x104e1e39d - core::fmt::write::hd42cb3dea57bae40
   2:        0x104e0351b - std::io::Write::write_fmt::ha39f6009af02b1d2
   3:        0x104e0758a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
   4:        0x104e0728a - std::panicking::default_hook::h04b06ec20c41bf02
   5:        0x104e07bdd - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
   6:        0x104e2cead - std::panicking::begin_panic::h3cfee2674b5b0d84
   7:        0x104da287c - glium::gl::missing_fn_panic::hff1ccfddaadbf6e3
   8:        0x104cea192 - glium::texture::any::new_texture::hf12b4c08a642b06c
   9:        0x104cf89c3 - valora::gpu::Gpu::build_texture::hb38598d85c84f205
  10:        0x104c9e24f - valora::run_fn::h95278922469ccfa0
  11:        0x104c9cf90 - art::main::h7e95a29569628757
  12:        0x104c9bdbb - std::rt::lang_start::{{closure}}::hc44a7c1958561f25
  13:        0x104e076a8 - std::panicking::try::do_call::hf2b35caddf59127c
  14:        0x104e09e0b - __rust_maybe_catch_panic
  15:        0x104e0805e - std::rt::lang_start_internal::h8e563903bf99e7c1
  16:        0x104c9cfe9 - main
```

**Comment by dp-pgh** [comment]
Ran into this issue as well, here is a full backtrace. Possibly related to Apple deprecating OpenGL and OpenCL for MacOS >= 10.14 in favor of proprietary technology.

```
$ RUST_BACKTRACE=full cargo run --release
    Finished release [optimized] target(s) in 1.08s

     Running `target/release/art`
thread 'main' panicked at 'gl function was not loaded', ~/art/target/release/build/glium-026141f5ee527852/out/gl_bindings.rs:2535:13
stack backtrace:
   0:        0x104e05795 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
   1:        0x104e1e39d - core::fmt::write::hd42cb3dea57bae40
   2:        0x104e0351b - std::io::Write::write_fmt::ha39f6009af02b1d2
   3:        0x104e0758a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
   4:        0x104e0728a - std::panicking::default_hook::h04b06ec20c41bf02
   5:        0x104e07bdd - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
   6:        0x104e2cead - std::panicking::begin_panic::h3cfee2674b5b0d84
   7:        0x104da287c - glium::gl::missing_fn_panic::hff1ccfddaadbf6e3
   8:        0x104cea192 - glium::texture::any::new_texture::hf12b4c08a642b06c
   9:        0x104cf89c3 - valora::gpu::Gpu::build_texture::hb38598d85c84f205
  10:        0x104c9e24f - valora::run_fn::h95278922469ccfa0
  11:        0x104c9cf90 - art::main::h7e95a29569628757
  12:        0x104c9bdbb - std::rt::lang_start::{{closure}}::hc44a7c1958561f25
  13:        0x104e076a8 - std::panicking::try::do_call::hf2b35caddf59127c
  14:        0x104e09e0b - __rust_maybe_catch_panic
  15:        0x104e0805e - std::rt::lang_start_internal::h8e563903bf99e7c1
  16:        0x104c9cfe9 - main
```

**Comment by turnage** [comment]
glium and glutin are updated. If the issue persists I suggest re-opening the [upstream issue](https://github.com/glium/glium/issues/1648).

**Comment by virtualritz** [comment]
Thank you for updating these dependencies, Payton.

Unfortunately it does persist. I couldn't reopen so I created a [new one](https://github.com/glium/glium/issues/1840).
